export const SET_VACCINE_PROOF = 'SET_VACCINE_PROOF';
export const SET_IDENTITY_PROOF = 'SET_IDENTITY_PROOF';
export const SET_PHOTO_PROOF = 'SET_PHOTO_PROOF';
export const SET_PERSONAL_INFO = 'SET_PERSONAL_INFO';
export const SUBMIT_DOCS = 'SUBMIT_DOCS';
